services:
  miniblue:
    image: ghcr.io/lonegunmanb/miniblue:sha-fba5d05
    ports:
      - "4566:4566"
      - "4567:4567"
      - "443:4567"
    environment:
      MINIBLUE_STORAGE_ENDPOINT: http://localhost:4566
      MINIBLUE_DISABLE_SHAREDKEY_AUTH: "1"
    deploy:
      resources:
        limits:
          memory: 512M
